live_config_reload = true

[font]
size = 13.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Light Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window]
dynamic_padding = false
option_as_alt="Both"

[mouse]
hide_when_typing = false

[shell]
program = "/bin/zsh"
args = ['-l']

