.\" Manpage for git-showtool
.TH man 1 "Mar 2016" "1.0" "git showtool man page"
.SH NAME
git showtool \- Run difftool on the latest commit 
.SH SYNOPSIS
git showtool [<options>] <commit> [--] [<path>...]
.SH DESCRIPTION
List each ref with the last commit on the ref sorted by commit date.
.SH OPTIONS
.TP
.TP
Same as git difftool.
.SH SEE ALSO
git-diftool(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Shane Matley
